### ISSUE TITLE
upgrade kafka client

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-connectors-kafka#150]
This is constrained by a Confluent lib that we use.
https://github.com/apache/pekko-connectors-kafka/blob/main/project/Versions.scala#L40

That lib has dependencies on a 'provided' version of the kafka client that is a Confluent release, not the Apache one.

@mdedetrich I believe that you are a Kafka contributor. Do you have any thoughts on how we should approach this?

**Comment by pjfanning** [comment]
@mdedetrich I think we need to address this before we really consider using scala steward

**Comment by mdedetrich** [comment]
I'll check this tomorrow, thanks for noticing

**Comment by mdedetrich** [comment]
So this library is not a kafka library, its a serializer and even though its from Confluent its license is Apache based https://mvnrepository.com/artifact/io.confluent/kafka-avro-serializer/7.6.0 .

There shouldn't be any issue here, and its common for users of Kafka to use this library as it provides avro based serdes for kafka messages

**Comment by pjfanning** [comment]
ok - it was feasible to merge all the Scala Steward PRs - a few required some minor additional changes - but all is well

My main issues with the Confluent project boil down to its non-standard maven repo and its weird in-house forks of the Apache Kafka libs. Nothing has assuaged this for me yet.
