### ISSUE TITLE
New package version

### ISSUE THREAD

**Issue by ricardohsd** [apache/pekko-connectors-kafka#189]
Hi folks,

Thanks for the work on maintaining the project. Recently I've had to migrate a project away from Akka due to the license change and the Pekko project was a life saver!

The latest package has Kafka 3.0.1 as dependency https://mvnrepository.com/artifact/org.apache.pekko/pekko-connectors-kafka_2.13/1.0.0
Are there plans to release a new package with support for Kafka >= 3.5?

**Comment by pjfanning** [comment]
We have upgraded in the main branch and have snapshots published with latest kafka jars as dependencies.
It seems that there is no hassle with using the using the newer kafka libs. Could you just try adding a build dependency in your own build to force the use of a newer kafka lib version?
We will probably release a 1.1.0-M1 release of this module in the next month or 2.

**Comment by jcavalieri** [comment]
@pjfanning, I'm in the same situation. I might have something working using the snapshots at https://repository.apache.org/content/groups/snapshots. However, I need to understand how long the snapshots are hosted. Would you happen to know?

**Comment by jcavalieri** [comment]
For reference: https://repository.apache.org/content/groups/snapshots/org/apache/pekko/pekko-connectors-kafka_2.13/

**Comment by jcavalieri** [comment]
Ah, I see. Just call out the dependency. Like this:
```
"org.apache.kafka"        % "kafka-clients"           % "3.7.0"
```

And it looks like we don't even need to use `dependencyOverrides`.

Thanks, @pjfanning.

**Comment by ricardohsd** [comment]
> We have upgraded in the main branch and have snapshots published with latest kafka jars as dependencies. It seems that there is no hassle with using the using the newer kafka libs. Could you just try adding a build dependency in your own build to force the use of a newer kafka lib version? We will probably release a 1.1.0-M1 release of this module in the next month or 2.

Thanks for the help. I've added it as a build dependency and it worked.
